### ISSUE TITLE
Error when dragging item tooltip markers

### ISSUE THREAD

**Issue by Meorawr** [Total-RP/Total-RP-3-Extended#174] opened 2020-08-01 23:32 UTC
This was reported on discord a few minutes ago:

> [00:12] Wikikinetic: Just encountered another glitch with item positioning:
> [00:15] Wikikinetic: When I have a character with an item, it slots into their equipment slot just fine, but when I try to drag the tooltip to the place I want the item positioned on the character, dropping the tooltip to position causes this Lua error to appear:

![](https://cdn.discordapp.com/attachments/242364964482842634/739260046642380836/Screen_Shot_2020-08-01_at_7.13.31_PM.png)

I think we're assuming that StartMoving is going to assign a TOPLEFT point when called, which isn't guaranteed since it'll instead anchor to the nearest screen corner; apparently moving the window to the top left of the screen does indeed help resolve the issue.

Also I dunno what the heck is actually being dragged, so I'm just calling them "item tooltip markers".

**Comment by Solanya** [comment] 2020-08-02 10:06
Duplicate of #153 :3

**Closed by Solanya** 2020-08-02 10:06 UTC
Labels: bug
